//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisUnimed.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class classificaco
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public classificaco()
        {
            this.materiais = new HashSet<materiai>();
        }
        
        [Key]
        [Display(Name="Código")]
        public long id { get; set; }

        [Display(Name="Descrição")]
        [Required(ErrorMessage="Descrição deve ser informada")]
        public string c_descricao { get; set; }

        [Display(Name="Data Inserção")]
        public Nullable<System.DateTime> sisdatai { get; set; }

        [Display(Name="Usuário Inserção")]
        public Nullable<long> sisusuarioi { get; set; }

        [Display(Name="Data Alteração")]
        public Nullable<System.DateTime> sisdataa { get; set; }

        [Display(Name="Usuário Alteração")]
        public Nullable<long> sisusuarioa { get; set; }
        public Nullable<System.DateTime> sisdatae { get; set; }
        public Nullable<long> sisusuarioe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<materiai> materiais { get; set; }
    }
    public class ListaClassificacao
    {
        public long id { get; set; }
        public string descricao { get; set; }
        public System.DateTime? sisdatai { get; set; }
        public string sisusuarioi { get; set; }
        public System.DateTime? sisdataa { get; set; }
        public string sisusuarioa { get; set; }
    }
}
