//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisUnimed.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class especialidade
    {
        [Key]
        [Display(Name="Código")]
        public long id { get; set; }

        [Display(Name="Código Alternativo")]
        [Required(ErrorMessage="Código Alternativo deve ser informado")]
        public string c_codigo { get; set; }

        [Display(Name="Descrição")]
        [Required(ErrorMessage="Descrição deve ser informada")]
        public string c_nome { get; set; }

        [Display(Name="Data de Inclusão")]
        public Nullable<System.DateTime> sisdatai { get; set; }

        [Display(Name="Usuário Inclusão")]
        public Nullable<long> sisusuarioi { get; set; }

        [Display(Name="Data de Alteração")]
        public Nullable<System.DateTime> sisdataa { get; set; }

        [Display(Name="Usuário Alteração")]
        public Nullable<long> sisusuarioa { get; set; }
        public Nullable<System.DateTime> sisdatae { get; set; }
        public Nullable<long> sisusuarioe { get; set; }
    }
    public class ListaEspecialidade
    {
        public long id { get; set; }
        public string c_codigo { get; set; }
        public string c_nome { get; set; }
        public System.DateTime? sisdatai { get; set; }
        public string sisusuarioi { get; set; }
        public System.DateTime? sisdataa { get; set; }
        public string sisusuarioa { get; set; } 
    }
}
