//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisUnimed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fornecedores_bancos
    {
        public long id { get; set; }
        public long banco { get; set; }
        public string c_agencia { get; set; }
        public string c_conta { get; set; }
        public string c_titular { get; set; }
        public string c_cidade { get; set; }
        public Nullable<long> estado { get; set; }
        public Nullable<System.DateTime> sisdatai { get; set; }
        public Nullable<long> sisusuarioi { get; set; }
        public Nullable<System.DateTime> sisdataa { get; set; }
        public Nullable<long> sisusuarioa { get; set; }
        public Nullable<System.DateTime> sisdatae { get; set; }
        public Nullable<long> sisusuarioe { get; set; }
    
        public virtual banco banco1 { get; set; }
        public virtual estado estado1 { get; set; }
    }
}
