//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisUnimed.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class fornecedores_enderecos
    {
        [Key]
        [Display(Name="Código")]
        public long id { get; set; }
        [Display(Name="Descrição")]
        [Required(ErrorMessage="Descrição deve ser informada")]
        public string c_descricao { get; set; }
        [Display(Name="Logradouro")]
        [Required(ErrorMessage="Logradouro deve ser informado")]
        public string c_logradouro { get; set; }
        [Display(Name="CEP")]
        [Required(ErrorMessage="CEP deve ser informado")]
        public string c_cep { get; set; }
        [Display(Name="Número")]
        [Required(ErrorMessage="Número deve ser informado")]
        public string c_numero { get; set; }
        [Display(Name="Bairro")]
        [Required(ErrorMessage="Bairro deve ser informado")]
        public string c_bairro { get; set; }
        [Display(Name="Complemento")]        
        public string c_complemento { get; set; }
        [Display(Name="Cidade")]
        [Required(ErrorMessage="Cidade deve ser informada")]
        public string c_cidade { get; set; }
        [Display(Name="UF")]
        public Nullable<long> estado { get; set; }
        [Display(Name="Data Inclusão")]
        public Nullable<System.DateTime> sisdatai { get; set; }
        [Display(Name="Usuário Inclusão")]
        public Nullable<long> sisusuarioi { get; set; }
        [Display(Name="Data Alteração")]
        public Nullable<System.DateTime> sisdataa { get; set; }
        [Display(Name="Usuário Alteração")]
        public Nullable<long> sisusuarioa { get; set; }
        public Nullable<System.DateTime> sisdatae { get; set; }
        public Nullable<long> sisusuarioe { get; set; }
    
        public virtual estado estado1 { get; set; }
    }
    public class ListaEndereco
    {
        public long id { get; set; }
        public string c_descricao { get; set; }
        public string c_logradoro { get; set; }
        public string c_numero { get; set; }
        public string c_bairro { get; set; }
        public string c_complemento { get; set; }
        public string c_cidade { get; set; }
        public string c_estado { get; set; }
        public string c_cep { get; set; }
        public System.DateTime? sisdatai { get; set; }
        public string sisusuarioi { get; set; }
        public System.DateTime? sisdataa { get; set; }
        public string sisusuarioa { get; set; }
    }
}
