//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisUnimed.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class fornecedores_telefones
    {
        [Key]
        [Display(Name="Código")]
        public long id { get; set; }
        [Display(Name="Fornecedor")]
        public long fornecedor { get; set; }
        [Display(Name="Contato")]
        [Required(ErrorMessage="Contato deve ser informado")]
        public string c_nome { get; set; }
        [Display(Name="Telefone")]
        [Required(ErrorMessage="Telefone deve ser informado")]
        public string c_telefone { get; set; }
        [Display(Name="Ramal/Setor")]
        [Required(ErrorMessage="Ramal/Setor deve ser informado")]
        public string c_setor { get; set; }
        [Display(Name="Data Inclusão")]
        public Nullable<System.DateTime> sisdatai { get; set; }
        [Display(Name="Usuário Inclusão")]
        public Nullable<long> sisusuarioi { get; set; }
        [Display(Name="Data Alteração")]
        public Nullable<System.DateTime> sisdataa { get; set; }
        [Display(Name="Usuário Alteração")]
        public Nullable<long> sisusuarioa { get; set; }
        public Nullable<System.DateTime> sisdatae { get; set; }
        public Nullable<long> sisusuarioe { get; set; }
    
        public virtual fornecedore fornecedore { get; set; }
    }
    public class ListaFornecedorTelefone
    {
        public long id { get; set; }
        public string fornecedor_nome { get; set; }
        public string c_telefone { get; set; }
        public string c_setor { get; set; }
        public string c_nome { get; set; }
        public System.DateTime? sisdatai { get; set; }
        public string sisusuarioi { get; set; }
        public System.DateTime? sisdataa { get; set; }
        public string sisusuarioa { get; set; }
        public long fornecedor { get; set; }
    }
}
