//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisUnimed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class grupo_permissao
    {
        public int id { get; set; }
        public int id_grupo { get; set; }
        public int operadora { get; set; }
        public int operadora_i { get; set; }
        public int operadora_a { get; set; }
        public int operadora_d { get; set; }
        public int grupo { get; set; }
        public int grupo_i { get; set; }
        public int grupo_a { get; set; }
        public int grupo_d { get; set; }
        public int grupo_permissao1 { get; set; }
        public int grupo_permissao_i { get; set; }
        public int grupo_permissao_a { get; set; }
        public int grupo_permissao_d { get; set; }
        public int usuario { get; set; }
        public int usuario_i { get; set; }
        public int usuario_a { get; set; }
        public int usuario_d { get; set; }
        public int usuario_permissao { get; set; }
        public int usuario_permissao_i { get; set; }
        public int usuario_permissao_a { get; set; }
        public int usuario_permissao_d { get; set; }
        public int especialidade { get; set; }
        public int especialidade_i { get; set; }
        public int especialidade_a { get; set; }
        public int especialidade_d { get; set; }
        public int classificacao { get; set; }
        public int classificacao_i { get; set; }
        public int classificacao_a { get; set; }
        public int classificacao_d { get; set; }
        public int marcas { get; set; }
        public int marcas_i { get; set; }
        public int marcas_a { get; set; }
        public int marcas_d { get; set; }
        public int unidades { get; set; }
        public int unidades_i { get; set; }
        public int unidades_a { get; set; }
        public int unidades_d { get; set; }
        public int procedimentos { get; set; }
        public int procedimentos_i { get; set; }
        public int procedimentos_a { get; set; }
        public int procedimentos_d { get; set; }
        public int regioes { get; set; }
        public int regioes_i { get; set; }
        public int regioes_a { get; set; }
        public int regioes_d { get; set; }
        public int estados { get; set; }
        public int estados_i { get; set; }
        public int estados_a { get; set; }
        public int estados_d { get; set; }
        public int bancos { get; set; }
        public int bancos_i { get; set; }
        public int bancos_a { get; set; }
        public int bancos_d { get; set; }
        public int fornecedores { get; set; }
        public int fornecedores_i { get; set; }
        public int fornecedores_a { get; set; }
        public int fornecedores_d { get; set; }
        public int materiais { get; set; }
        public int materiais_i { get; set; }
        public int materiais_a { get; set; }
        public int materiais_d { get; set; }
    
        public virtual grupo grupo1 { get; set; }
    }
}
