//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisUnimed.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class marca
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public marca()
        {
            this.marcas_operadoras = new HashSet<marcas_operadoras>();
            this.materiais = new HashSet<materiai>();
        }
        [Key]
        [Display(Name="Código")]        
        public long id { get; set; }

        [Display(Name="Descrição")]
        [Required(ErrorMessage="Descrição deve ser informada")]
        public string c_nome { get; set; }

        [Display(Name="Situação")]
        [Required(ErrorMessage="Situação deve ser informada")]
        public int f_situacao { get; set; }

        [Display(Name="Data Inclusão")]
        public Nullable<System.DateTime> sisdatai { get; set; }
        [Display(Name="Usuário Inclusão")]
        public Nullable<long> sisusuarioi { get; set; }
        [Display(Name="Data Alteração")]
        public Nullable<System.DateTime> sisdataa { get; set; }
        [Display(Name="Usuário Alteração")]
        public Nullable<long> sisusuarioa { get; set; }
        public Nullable<System.DateTime> sisdatae { get; set; }
        public Nullable<long> sisusuarioe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<marcas_operadoras> marcas_operadoras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<materiai> materiais { get; set; }
    }
    public class ListaMarca
    {
        public long id { get; set; }
        public string c_nome { get; set; }
        public string f_situacao { get; set; }
        public System.DateTime? sisdatai { get; set; }
        public string sisusuarioi { get; set; }
        public System.DateTime? sisdataa { get; set; }
        public string sisusuarioa { get; set; }
    }
    public class ViewModelDetalheMarcaOp
    {
        public marca Vmarca { get; set; }
        public marcas_operadoras VmarcaOperadora { get; set; }
    }
}
