//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisUnimed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class materiai
    {
        public long id { get; set; }
        public string c_tnumm { get; set; }
        public string c_cod_ref_fabr { get; set; }
        public string c_nome_material { get; set; }
        public string c_registro_anvisa { get; set; }
        public Nullable<System.DateTime> d_validade { get; set; }
        public Nullable<System.DateTime> d_inicio_vigencia { get; set; }
        public Nullable<System.DateTime> d_fim_vigencia { get; set; }
        public Nullable<long> fornecedor { get; set; }
        public Nullable<decimal> v_preco { get; set; }
        public int f_status { get; set; }
        public bool f_distribuidor_exclusivo { get; set; }
        public bool f_nao_negociado { get; set; }
        public Nullable<long> classificacao { get; set; }
        public Nullable<long> marca { get; set; }
        public int f_origem { get; set; }
        public Nullable<long> unidade { get; set; }
        public string c_nome_comercial { get; set; }
        public string c_codigo_tuss { get; set; }
        public string c_composicao { get; set; }
        public string c_descricao_generica { get; set; }
        public string c_justificativa_alteracao { get; set; }
        public Nullable<System.DateTime> sisdatai { get; set; }
        public Nullable<long> sisusuarioi { get; set; }
        public Nullable<System.DateTime> sisdataa { get; set; }
        public Nullable<long> sisusuarioa { get; set; }
        public Nullable<System.DateTime> sisdatae { get; set; }
        public Nullable<long> sisusuarioe { get; set; }
    
        public virtual classificaco classificaco { get; set; }
        public virtual fornecedore fornecedore { get; set; }
        public virtual marca marca1 { get; set; }
        public virtual unidade unidade1 { get; set; }
    }
}
