//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisUnimed.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UnimedEntities1 : DbContext
    {
        public UnimedEntities1()
            : base("name=UnimedEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<grupo> grupoes { get; set; }
        public virtual DbSet<grupo_permissao> grupo_permissao { get; set; }
        public virtual DbSet<operadora> operadoras { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
        public virtual DbSet<usuario_permissao> usuario_permissao { get; set; }
    }
}
