//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisUnimed.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UnimedEntities1 : DbContext
    {
        public UnimedEntities1()
            : base("name=UnimedEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<grupo> grupoes { get; set; }
        public virtual DbSet<grupo_permissao> grupo_permissao { get; set; }
        public virtual DbSet<operadora> operadoras { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
        public virtual DbSet<usuario_permissao> usuario_permissao { get; set; }
        public virtual DbSet<classificaco> classificacoes { get; set; }
        public virtual DbSet<especialidade> especialidades { get; set; }
        public virtual DbSet<fornecedore> fornecedores { get; set; }
        public virtual DbSet<importacao_xls> importacao_xls { get; set; }
        public virtual DbSet<marca> marcas { get; set; }
        public virtual DbSet<marcas_operadoras> marcas_operadoras { get; set; }
        public virtual DbSet<materiai> materiais { get; set; }
        public virtual DbSet<operadora1> operadoras1 { get; set; }
        public virtual DbSet<unidade> unidades { get; set; }
        public virtual DbSet<banco> bancos { get; set; }
        public virtual DbSet<estado> estados { get; set; }
        public virtual DbSet<fornecedores_anexos> fornecedores_anexos { get; set; }
        public virtual DbSet<fornecedores_bancos> fornecedores_bancos { get; set; }
        public virtual DbSet<fornecedores_emails> fornecedores_emails { get; set; }
        public virtual DbSet<fornecedores_enderecos> fornecedores_enderecos { get; set; }
        public virtual DbSet<fornecedores_materiais> fornecedores_materiais { get; set; }
        public virtual DbSet<fornecedores_regioes> fornecedores_regioes { get; set; }
        public virtual DbSet<fornecedores_telefones> fornecedores_telefones { get; set; }
        public virtual DbSet<materiais_informacoes> materiais_informacoes { get; set; }
        public virtual DbSet<materiais_procedimentos> materiais_procedimentos { get; set; }
        public virtual DbSet<materiais_similares> materiais_similares { get; set; }
        public virtual DbSet<negociaco> negociacoes { get; set; }
        public virtual DbSet<negociacoes_chat> negociacoes_chat { get; set; }
        public virtual DbSet<negociacoes_materiais> negociacoes_materiais { get; set; }
        public virtual DbSet<negociacoes_negociadores> negociacoes_negociadores { get; set; }
        public virtual DbSet<negociadore> negociadores { get; set; }
        public virtual DbSet<procedimento> procedimentos { get; set; }
        public virtual DbSet<regio> regioes { get; set; }
    }
}
