//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisUnimed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class negociaco
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public negociaco()
        {
            this.negociacoes_chat = new HashSet<negociacoes_chat>();
            this.negociacoes_materiais = new HashSet<negociacoes_materiais>();
            this.negociacoes_negociadores = new HashSet<negociacoes_negociadores>();
        }
    
        public long id { get; set; }
        public int f_status_negociacao { get; set; }
        public string c_descricao { get; set; }
        public Nullable<System.DateTime> d_inicio_fornecedor { get; set; }
        public Nullable<System.DateTime> d_termino_fornecedor { get; set; }
        public Nullable<System.DateTime> d_inicio_operadora { get; set; }
        public Nullable<System.DateTime> d_termino_operadora { get; set; }
        public Nullable<long> fornecedor { get; set; }
        public string c_reuniao { get; set; }
        public string c_observacoes { get; set; }
        public Nullable<System.DateTime> sisdatai { get; set; }
        public Nullable<long> sisusuarioi { get; set; }
        public Nullable<System.DateTime> sisdataa { get; set; }
        public Nullable<long> sisusuarioa { get; set; }
        public Nullable<System.DateTime> sisdatae { get; set; }
        public Nullable<long> sisusuarioe { get; set; }
    
        public virtual fornecedore fornecedore { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<negociacoes_chat> negociacoes_chat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<negociacoes_materiais> negociacoes_materiais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<negociacoes_negociadores> negociacoes_negociadores { get; set; }
    }
    public class ListaNegociacaoF
    {
        public long id { get; set; }        
        public string c_descricao { get; set; }
    }
}
