//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisUnimed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class negociacoes_materiais
    {
        public long id { get; set; }
        public long negociacao { get; set; }
        public long material { get; set; }
        public Nullable<decimal> v_valor_proposto { get; set; }
        public Nullable<decimal> v_valor_final { get; set; }
        public Nullable<decimal> v_preco_operadora { get; set; }
        public Nullable<decimal> v_qtd_ano { get; set; }
        public string c_observacao { get; set; }
        public string c_justificativa { get; set; }
        public Nullable<System.DateTime> sisdatai { get; set; }
        public Nullable<long> sisusuarioi { get; set; }
        public Nullable<System.DateTime> sisdataa { get; set; }
        public Nullable<long> sisusuarioa { get; set; }
        public Nullable<System.DateTime> sisdatae { get; set; }
        public Nullable<long> sisusuarioe { get; set; }
    
        public virtual materiai materiai { get; set; }
        public virtual negociaco negociaco { get; set; }
    }
}
