//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisUnimed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario_permissao
    {
        public int id { get; set; }
        public int id_usuario { get; set; }
        public int operadora { get; set; }
        public int operadora_i { get; set; }
        public int operadora_a { get; set; }
        public int operadora_d { get; set; }
        public int grupo { get; set; }
        public int grupo_i { get; set; }
        public int grupo_a { get; set; }
        public int grupo_d { get; set; }
        public int grupo_permissao { get; set; }
        public int grupo_permissao_i { get; set; }
        public int grupo_permissao_a { get; set; }
        public int grupo_permissao_d { get; set; }
        public int usuario { get; set; }
        public int usuario_i { get; set; }
        public int usuario_a { get; set; }
        public int usuario_d { get; set; }
        public int usuario_permissao1 { get; set; }
        public int usuario_permissao_i { get; set; }
        public int usuario_permissao_a { get; set; }
        public int usuario_permissao_d { get; set; }
    
        public virtual usuario usuario1 { get; set; }
    }
}
